2025-10-19 17:45:45,771 - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: connecting to localhost:9092 [('::1', 9092, 0, 0) IPv6]
2025-10-19 17:45:45,785 - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=localhost:9092 <checking_api_versions_recv> [IPv6 ('::1', 9092, 0, 0)]>: Broker version identified as 2.6
2025-10-19 17:45:45,786 - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=localhost:9092 <connected> [IPv6 ('::1', 9092, 0, 0)]>: Connection complete.
2025-10-19 17:45:46,635 - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: connecting to localhost:9092 [('::1', 9092, 0, 0) IPv6]
2025-10-19 17:45:46,636 - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:9092 <connected> [IPv6 ('::1', 9092, 0, 0)]>: Connection complete.
2025-10-19 17:45:46,636 - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=localhost:9092 <connected> [IPv6 ('::1', 9092, 0, 0)]>: Closing connection. 
2025-10-19 17:45:46,648 - Topic traffic_data not found in cluster metadata
2025-10-19 17:45:46,773 - {'camera': 'HCMC_5deb576d1dc17d7c5515acfa', 'timestamp': '2025-10-19T10:45:46.634576', 'counts': {'car': 18, 'motorcycle': 3}}
2025-10-19 17:45:52,257 - {'camera': 'HCMC_5deb576d1dc17d7c5515acfa', 'timestamp': '2025-10-19T10:45:52.252648', 'counts': {'car': 18, 'motorcycle': 3}}
2025-10-19 17:45:57,784 - {'camera': 'HCMC_5deb576d1dc17d7c5515acfa', 'timestamp': '2025-10-19T10:45:57.778381', 'counts': {'car': 25, 'truck': 2, 'motorcycle': 20}}
2025-10-19 17:46:03,376 - {'camera': 'HCMC_5deb576d1dc17d7c5515acfa', 'timestamp': '2025-10-19T10:46:03.372329', 'counts': {'car': 25, 'truck': 2, 'motorcycle': 20}}
2025-10-19 17:46:08,994 - {'camera': 'HCMC_5deb576d1dc17d7c5515acfa', 'timestamp': '2025-10-19T10:46:08.991065', 'counts': {'car': 22, 'bus': 1, 'motorcycle': 14, 'truck': 1}}
2025-10-19 17:46:14,607 - {'camera': 'HCMC_5deb576d1dc17d7c5515acfa', 'timestamp': '2025-10-19T10:46:14.603118', 'counts': {'car': 22, 'bus': 1, 'motorcycle': 14, 'truck': 1}}
2025-10-19 17:46:20,146 - {'camera': 'HCMC_5deb576d1dc17d7c5515acfa', 'timestamp': '2025-10-19T10:46:20.142180', 'counts': {'car': 22, 'bus': 1, 'motorcycle': 14, 'truck': 1}}
2025-10-19 17:46:25,633 - {'camera': 'HCMC_5deb576d1dc17d7c5515acfa', 'timestamp': '2025-10-19T10:46:25.629394', 'counts': {'car': 24, 'motorcycle': 14}}
2025-10-19 17:46:31,123 - {'camera': 'HCMC_5deb576d1dc17d7c5515acfa', 'timestamp': '2025-10-19T10:46:31.119780', 'counts': {'car': 24, 'motorcycle': 14}}
2025-10-19 17:46:36,806 - {'camera': 'HCMC_5deb576d1dc17d7c5515acfa', 'timestamp': '2025-10-19T10:46:36.802732', 'counts': {'bus': 1, 'motorcycle': 50, 'car': 15}}
2025-10-19 17:46:42,319 - {'camera': 'HCMC_5deb576d1dc17d7c5515acfa', 'timestamp': '2025-10-19T10:46:42.316478', 'counts': {'bus': 1, 'motorcycle': 50, 'car': 15}}
2025-10-19 17:46:47,837 - {'camera': 'HCMC_5deb576d1dc17d7c5515acfa', 'timestamp': '2025-10-19T10:46:47.833867', 'counts': {'car': 19, 'motorcycle': 15, 'truck': 1}}
2025-10-19 17:46:53,357 - {'camera': 'HCMC_5deb576d1dc17d7c5515acfa', 'timestamp': '2025-10-19T10:46:53.353632', 'counts': {'car': 19, 'motorcycle': 15, 'truck': 1}}
2025-10-19 17:46:58,951 - {'camera': 'HCMC_5deb576d1dc17d7c5515acfa', 'timestamp': '2025-10-19T10:46:58.947551', 'counts': {'car': 18, 'motorcycle': 17}}
2025-10-19 17:47:04,562 - {'camera': 'HCMC_5deb576d1dc17d7c5515acfa', 'timestamp': '2025-10-19T10:47:04.557891', 'counts': {'car': 18, 'motorcycle': 17}}
2025-10-19 17:47:10,105 - {'camera': 'HCMC_5deb576d1dc17d7c5515acfa', 'timestamp': '2025-10-19T10:47:10.101229', 'counts': {'car': 18, 'motorcycle': 17}}
2025-10-19 17:47:15,668 - {'camera': 'HCMC_5deb576d1dc17d7c5515acfa', 'timestamp': '2025-10-19T10:47:15.664674', 'counts': {'car': 22, 'motorcycle': 22}}
2025-10-19 17:47:21,168 - {'camera': 'HCMC_5deb576d1dc17d7c5515acfa', 'timestamp': '2025-10-19T10:47:21.164667', 'counts': {'car': 22, 'motorcycle': 22}}
2025-10-19 17:47:26,708 - {'camera': 'HCMC_5deb576d1dc17d7c5515acfa', 'timestamp': '2025-10-19T10:47:26.704298', 'counts': {'car': 30, 'motorcycle': 9}}
2025-10-19 17:47:32,333 - {'camera': 'HCMC_5deb576d1dc17d7c5515acfa', 'timestamp': '2025-10-19T10:47:32.329132', 'counts': {'car': 30, 'motorcycle': 9}}
2025-10-19 17:47:37,981 - {'camera': 'HCMC_5deb576d1dc17d7c5515acfa', 'timestamp': '2025-10-19T10:47:37.975197', 'counts': {'car': 41, 'motorcycle': 8}}
2025-10-19 17:47:43,498 - {'camera': 'HCMC_5deb576d1dc17d7c5515acfa', 'timestamp': '2025-10-19T10:47:43.493505', 'counts': {'car': 41, 'motorcycle': 8}}
2025-10-19 17:47:49,041 - {'camera': 'HCMC_5deb576d1dc17d7c5515acfa', 'timestamp': '2025-10-19T10:47:49.037238', 'counts': {'car': 19, 'motorcycle': 46, 'truck': 1}}
2025-10-19 17:47:54,540 - {'camera': 'HCMC_5deb576d1dc17d7c5515acfa', 'timestamp': '2025-10-19T10:47:54.536102', 'counts': {'car': 19, 'motorcycle': 46, 'truck': 1}}
2025-10-19 17:48:00,197 - {'camera': 'HCMC_5deb576d1dc17d7c5515acfa', 'timestamp': '2025-10-19T10:48:00.194090', 'counts': {'car': 19, 'motorcycle': 46, 'truck': 1}}
2025-10-19 17:48:05,706 - {'camera': 'HCMC_5deb576d1dc17d7c5515acfa', 'timestamp': '2025-10-19T10:48:05.703040', 'counts': {'car': 36, 'motorcycle': 32, 'truck': 5, 'bus': 1}}
2025-10-19 17:48:07,590 - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:9092 <connected> [IPv6 ('::1', 9092, 0, 0)]>: Closing connection. 
2025-10-19 18:16:17,512 - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: connecting to localhost:9092 [('::1', 9092, 0, 0) IPv6]
2025-10-19 18:16:17,524 - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=localhost:9092 <checking_api_versions_recv> [IPv6 ('::1', 9092, 0, 0)]>: Broker version identified as 2.6
2025-10-19 18:16:17,525 - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=localhost:9092 <connected> [IPv6 ('::1', 9092, 0, 0)]>: Connection complete.
2025-10-19 18:16:25,608 - DNS lookup failed for kafka:9092, exception was [Errno 11001] getaddrinfo failed. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
2025-10-19 18:16:25,610 - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=kafka:9092 <connecting> [unspecified None]>: DNS lookup failed for kafka:9092 (0)
2025-10-19 18:16:25,610 - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=kafka:9092 <connecting> [unspecified None]>: Closing connection. KafkaConnectionError: DNS failure
2025-10-19 18:16:25,611 - Node 1 connection failed -- refreshing metadata
2025-10-19 18:16:28,373 - DNS lookup failed for kafka:9092, exception was [Errno 11001] getaddrinfo failed. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
2025-10-19 18:16:28,373 - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=kafka:9092 <connecting> [unspecified None]>: DNS lookup failed for kafka:9092 (0)
2025-10-19 18:16:28,373 - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=kafka:9092 <connecting> [unspecified None]>: Closing connection. KafkaConnectionError: DNS failure
2025-10-19 18:16:28,373 - Node 1 connection failed -- refreshing metadata
2025-10-19 18:16:31,125 - DNS lookup failed for kafka:9092, exception was [Errno 11001] getaddrinfo failed. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
2025-10-19 18:16:31,125 - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=kafka:9092 <connecting> [unspecified None]>: DNS lookup failed for kafka:9092 (0)
2025-10-19 18:16:31,125 - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=kafka:9092 <connecting> [unspecified None]>: Closing connection. KafkaConnectionError: DNS failure
2025-10-19 18:16:31,126 - Node 1 connection failed -- refreshing metadata
2025-10-19 18:16:33,882 - DNS lookup failed for kafka:9092, exception was [Errno 11001] getaddrinfo failed. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
2025-10-19 18:16:33,882 - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=kafka:9092 <connecting> [unspecified None]>: DNS lookup failed for kafka:9092 (0)
2025-10-19 18:16:33,882 - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=kafka:9092 <connecting> [unspecified None]>: Closing connection. KafkaConnectionError: DNS failure
2025-10-19 18:16:33,882 - Node 1 connection failed -- refreshing metadata
2025-10-19 18:16:36,625 - DNS lookup failed for kafka:9092, exception was [Errno 11001] getaddrinfo failed. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
2025-10-19 18:16:36,625 - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=kafka:9092 <connecting> [unspecified None]>: DNS lookup failed for kafka:9092 (0)
2025-10-19 18:16:36,625 - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=kafka:9092 <connecting> [unspecified None]>: Closing connection. KafkaConnectionError: DNS failure
2025-10-19 18:16:36,625 - Node 1 connection failed -- refreshing metadata
2025-10-19 18:16:39,383 - DNS lookup failed for kafka:9092, exception was [Errno 11001] getaddrinfo failed. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
2025-10-19 18:16:39,383 - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=kafka:9092 <connecting> [unspecified None]>: DNS lookup failed for kafka:9092 (0)
2025-10-19 18:16:39,383 - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=kafka:9092 <connecting> [unspecified None]>: Closing connection. KafkaConnectionError: DNS failure
2025-10-19 18:16:39,383 - Node 1 connection failed -- refreshing metadata
2025-10-19 18:16:46,249 - DNS lookup failed for kafka:9092, exception was [Errno 11001] getaddrinfo failed. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
2025-10-19 18:16:46,249 - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=kafka:9092 <connecting> [unspecified None]>: DNS lookup failed for kafka:9092 (0)
2025-10-19 18:16:46,249 - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=kafka:9092 <connecting> [unspecified None]>: Closing connection. KafkaConnectionError: DNS failure
2025-10-19 18:16:46,249 - Node 1 connection failed -- refreshing metadata
2025-10-19 18:16:49,013 - DNS lookup failed for kafka:9092, exception was [Errno 11001] getaddrinfo failed. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
2025-10-19 18:16:49,014 - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=kafka:9092 <connecting> [unspecified None]>: DNS lookup failed for kafka:9092 (0)
2025-10-19 18:16:49,014 - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=kafka:9092 <connecting> [unspecified None]>: Closing connection. KafkaConnectionError: DNS failure
2025-10-19 18:16:49,014 - Node 1 connection failed -- refreshing metadata
2025-10-19 18:16:54,865 - DNS lookup failed for kafka:9092, exception was [Errno 11001] getaddrinfo failed. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
2025-10-19 18:16:54,865 - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=kafka:9092 <connecting> [unspecified None]>: DNS lookup failed for kafka:9092 (0)
2025-10-19 18:16:54,865 - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=kafka:9092 <connecting> [unspecified None]>: Closing connection. KafkaConnectionError: DNS failure
2025-10-19 18:16:54,865 - Node 1 connection failed -- refreshing metadata
2025-10-19 18:17:12,580 - DNS lookup failed for kafka:9092, exception was [Errno 11001] getaddrinfo failed. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
2025-10-19 18:17:12,580 - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=kafka:9092 <connecting> [unspecified None]>: DNS lookup failed for kafka:9092 (0)
2025-10-19 18:17:12,580 - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=kafka:9092 <connecting> [unspecified None]>: Closing connection. KafkaConnectionError: DNS failure
2025-10-19 18:17:12,580 - Node 1 connection failed -- refreshing metadata
2025-10-19 18:17:18,374 - Error: KafkaTimeoutError: Failed to update metadata after 60.0 secs.
2025-10-19 18:17:42,398 - DNS lookup failed for kafka:9092, exception was [Errno 11001] getaddrinfo failed. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
2025-10-19 18:17:42,399 - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=kafka:9092 <connecting> [unspecified None]>: DNS lookup failed for kafka:9092 (0)
2025-10-19 18:17:42,399 - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=kafka:9092 <connecting> [unspecified None]>: Closing connection. KafkaConnectionError: DNS failure
2025-10-19 18:17:42,399 - Node 1 connection failed -- refreshing metadata
2025-10-19 18:18:15,818 - DNS lookup failed for kafka:9092, exception was [Errno 11001] getaddrinfo failed. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
2025-10-19 18:18:15,818 - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=kafka:9092 <connecting> [unspecified None]>: DNS lookup failed for kafka:9092 (0)
2025-10-19 18:18:15,818 - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=kafka:9092 <connecting> [unspecified None]>: Closing connection. KafkaConnectionError: DNS failure
2025-10-19 18:18:15,818 - Node 1 connection failed -- refreshing metadata
2025-10-19 18:18:23,894 - Error: KafkaTimeoutError: Failed to update metadata after 60.0 secs.
2025-10-19 18:18:43,543 - DNS lookup failed for kafka:9092, exception was [Errno 11001] getaddrinfo failed. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
2025-10-19 18:18:43,543 - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=kafka:9092 <connecting> [unspecified None]>: DNS lookup failed for kafka:9092 (0)
2025-10-19 18:18:43,543 - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=kafka:9092 <connecting> [unspecified None]>: Closing connection. KafkaConnectionError: DNS failure
2025-10-19 18:18:43,544 - Node 1 connection failed -- refreshing metadata
2025-10-19 18:19:15,157 - DNS lookup failed for kafka:9092, exception was [Errno 11001] getaddrinfo failed. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
2025-10-19 18:19:15,157 - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=kafka:9092 <connecting> [unspecified None]>: DNS lookup failed for kafka:9092 (0)
2025-10-19 18:19:15,157 - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=kafka:9092 <connecting> [unspecified None]>: Closing connection. KafkaConnectionError: DNS failure
2025-10-19 18:19:15,158 - Node 1 connection failed -- refreshing metadata
2025-10-19 18:24:09,827 - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: connecting to localhost:9092 [('::1', 9092, 0, 0) IPv6]
2025-10-19 18:24:09,838 - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=localhost:9092 <checking_api_versions_recv> [IPv6 ('::1', 9092, 0, 0)]>: Broker version identified as 2.6
2025-10-19 18:24:09,839 - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=localhost:9092 <connected> [IPv6 ('::1', 9092, 0, 0)]>: Connection complete.
2025-10-19 18:24:17,703 - DNS lookup failed for kafka:9092, exception was [Errno 11001] getaddrinfo failed. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
2025-10-19 18:24:17,703 - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=kafka:9092 <connecting> [unspecified None]>: DNS lookup failed for kafka:9092 (0)
2025-10-19 18:24:17,703 - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=kafka:9092 <connecting> [unspecified None]>: Closing connection. KafkaConnectionError: DNS failure
2025-10-19 18:24:17,703 - Node 1 connection failed -- refreshing metadata
2025-10-19 18:24:20,470 - DNS lookup failed for kafka:9092, exception was [Errno 11001] getaddrinfo failed. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
2025-10-19 18:24:20,470 - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=kafka:9092 <connecting> [unspecified None]>: DNS lookup failed for kafka:9092 (0)
2025-10-19 18:24:20,470 - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=kafka:9092 <connecting> [unspecified None]>: Closing connection. KafkaConnectionError: DNS failure
2025-10-19 18:24:20,471 - Node 1 connection failed -- refreshing metadata
2025-10-19 18:24:23,245 - DNS lookup failed for kafka:9092, exception was [Errno 11001] getaddrinfo failed. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
2025-10-19 18:24:23,245 - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=kafka:9092 <connecting> [unspecified None]>: DNS lookup failed for kafka:9092 (0)
2025-10-19 18:24:23,245 - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=kafka:9092 <connecting> [unspecified None]>: Closing connection. KafkaConnectionError: DNS failure
2025-10-19 18:24:23,245 - Node 1 connection failed -- refreshing metadata
2025-10-19 18:24:26,008 - DNS lookup failed for kafka:9092, exception was [Errno 11001] getaddrinfo failed. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
2025-10-19 18:24:26,008 - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=kafka:9092 <connecting> [unspecified None]>: DNS lookup failed for kafka:9092 (0)
2025-10-19 18:24:26,008 - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=kafka:9092 <connecting> [unspecified None]>: Closing connection. KafkaConnectionError: DNS failure
2025-10-19 18:24:26,008 - Node 1 connection failed -- refreshing metadata
2025-10-19 18:24:28,767 - DNS lookup failed for kafka:9092, exception was [Errno 11001] getaddrinfo failed. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
2025-10-19 18:24:28,767 - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=kafka:9092 <connecting> [unspecified None]>: DNS lookup failed for kafka:9092 (0)
2025-10-19 18:24:28,767 - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=kafka:9092 <connecting> [unspecified None]>: Closing connection. KafkaConnectionError: DNS failure
2025-10-19 18:24:28,768 - Node 1 connection failed -- refreshing metadata
2025-10-19 18:24:31,526 - DNS lookup failed for kafka:9092, exception was [Errno 11001] getaddrinfo failed. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
2025-10-19 18:24:31,526 - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=kafka:9092 <connecting> [unspecified None]>: DNS lookup failed for kafka:9092 (0)
2025-10-19 18:24:31,527 - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=kafka:9092 <connecting> [unspecified None]>: Closing connection. KafkaConnectionError: DNS failure
2025-10-19 18:24:31,527 - Node 1 connection failed -- refreshing metadata
2025-10-19 18:24:38,391 - DNS lookup failed for kafka:9092, exception was [Errno 11001] getaddrinfo failed. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
2025-10-19 18:24:38,392 - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=kafka:9092 <connecting> [unspecified None]>: DNS lookup failed for kafka:9092 (0)
2025-10-19 18:24:38,392 - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=kafka:9092 <connecting> [unspecified None]>: Closing connection. KafkaConnectionError: DNS failure
2025-10-19 18:24:38,392 - Node 1 connection failed -- refreshing metadata
2025-10-19 18:24:41,157 - DNS lookup failed for kafka:9092, exception was [Errno 11001] getaddrinfo failed. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
2025-10-19 18:24:41,157 - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=kafka:9092 <connecting> [unspecified None]>: DNS lookup failed for kafka:9092 (0)
2025-10-19 18:24:41,157 - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=kafka:9092 <connecting> [unspecified None]>: Closing connection. KafkaConnectionError: DNS failure
2025-10-19 18:24:41,158 - Node 1 connection failed -- refreshing metadata
2025-10-19 18:24:48,564 - DNS lookup failed for kafka:9092, exception was [Errno 11001] getaddrinfo failed. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
2025-10-19 18:24:48,564 - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=kafka:9092 <connecting> [unspecified None]>: DNS lookup failed for kafka:9092 (0)
2025-10-19 18:24:48,564 - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=kafka:9092 <connecting> [unspecified None]>: Closing connection. KafkaConnectionError: DNS failure
2025-10-19 18:24:48,564 - Node 1 connection failed -- refreshing metadata
2025-10-19 18:25:05,190 - DNS lookup failed for kafka:9092, exception was [Errno 11001] getaddrinfo failed. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
2025-10-19 18:25:05,190 - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=kafka:9092 <connecting> [unspecified None]>: DNS lookup failed for kafka:9092 (0)
2025-10-19 18:25:05,190 - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=kafka:9092 <connecting> [unspecified None]>: Closing connection. KafkaConnectionError: DNS failure
2025-10-19 18:25:05,191 - Node 1 connection failed -- refreshing metadata
2025-10-19 18:25:10,459 - Error: KafkaTimeoutError: Failed to update metadata after 60.0 secs.
2025-10-19 18:25:27,591 - DNS lookup failed for kafka:9092, exception was [Errno 11001] getaddrinfo failed. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
2025-10-19 18:25:27,592 - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=kafka:9092 <connecting> [unspecified None]>: DNS lookup failed for kafka:9092 (0)
2025-10-19 18:25:27,592 - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=kafka:9092 <connecting> [unspecified None]>: Closing connection. KafkaConnectionError: DNS failure
2025-10-19 18:25:27,592 - Node 1 connection failed -- refreshing metadata
2025-10-19 18:26:03,260 - DNS lookup failed for kafka:9092, exception was [Errno 11001] getaddrinfo failed. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
2025-10-19 18:26:03,261 - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=kafka:9092 <connecting> [unspecified None]>: DNS lookup failed for kafka:9092 (0)
2025-10-19 18:26:03,261 - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=kafka:9092 <connecting> [unspecified None]>: Closing connection. KafkaConnectionError: DNS failure
2025-10-19 18:26:03,261 - Node 1 connection failed -- refreshing metadata
2025-10-19 18:26:15,973 - Error: KafkaTimeoutError: Failed to update metadata after 60.0 secs.
2025-10-19 18:26:34,613 - DNS lookup failed for kafka:9092, exception was [Errno 11001] getaddrinfo failed. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
2025-10-19 18:26:34,614 - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=kafka:9092 <connecting> [unspecified None]>: DNS lookup failed for kafka:9092 (0)
2025-10-19 18:26:34,614 - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=kafka:9092 <connecting> [unspecified None]>: Closing connection. KafkaConnectionError: DNS failure
2025-10-19 18:26:34,614 - Node 1 connection failed -- refreshing metadata
2025-10-19 18:27:07,269 - DNS lookup failed for kafka:9092, exception was [Errno 11001] getaddrinfo failed. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
2025-10-19 18:27:07,269 - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=kafka:9092 <connecting> [unspecified None]>: DNS lookup failed for kafka:9092 (0)
2025-10-19 18:27:07,269 - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=kafka:9092 <connecting> [unspecified None]>: Closing connection. KafkaConnectionError: DNS failure
2025-10-19 18:27:07,269 - Node 1 connection failed -- refreshing metadata
2025-10-19 18:27:07,269 - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=localhost:9092 <connected> [IPv6 ('::1', 9092, 0, 0)]>: Closing connection. KafkaConnectionError: Socket EVENT_READ without in-flight-requests
2025-10-19 18:27:28,913 - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: connecting to localhost:9092 [('::1', 9092, 0, 0) IPv6]
2025-10-19 18:33:10,585 - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: connecting to localhost:9092 [('::1', 9092, 0, 0) IPv6]
2025-10-19 18:33:10,595 - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=localhost:9092 <checking_api_versions_recv> [IPv6 ('::1', 9092, 0, 0)]>: Broker version identified as 2.6
2025-10-19 18:33:10,595 - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=localhost:9092 <connected> [IPv6 ('::1', 9092, 0, 0)]>: Connection complete.
2025-10-19 18:33:18,443 - DNS lookup failed for kafka:9092, exception was [Errno 11001] getaddrinfo failed. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
2025-10-19 18:33:18,443 - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=kafka:9092 <connecting> [unspecified None]>: DNS lookup failed for kafka:9092 (0)
2025-10-19 18:33:18,443 - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=kafka:9092 <connecting> [unspecified None]>: Closing connection. KafkaConnectionError: DNS failure
2025-10-19 18:33:18,443 - Node 1 connection failed -- refreshing metadata
2025-10-19 18:33:21,167 - DNS lookup failed for kafka:9092, exception was [Errno 11001] getaddrinfo failed. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
2025-10-19 18:33:21,167 - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=kafka:9092 <connecting> [unspecified None]>: DNS lookup failed for kafka:9092 (0)
2025-10-19 18:33:21,167 - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=kafka:9092 <connecting> [unspecified None]>: Closing connection. KafkaConnectionError: DNS failure
2025-10-19 18:33:21,167 - Node 1 connection failed -- refreshing metadata
2025-10-19 18:33:23,921 - DNS lookup failed for kafka:9092, exception was [Errno 11001] getaddrinfo failed. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
2025-10-19 18:33:23,921 - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=kafka:9092 <connecting> [unspecified None]>: DNS lookup failed for kafka:9092 (0)
2025-10-19 18:33:23,921 - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=kafka:9092 <connecting> [unspecified None]>: Closing connection. KafkaConnectionError: DNS failure
2025-10-19 18:33:23,922 - Node 1 connection failed -- refreshing metadata
2025-10-19 18:33:26,686 - DNS lookup failed for kafka:9092, exception was [Errno 11001] getaddrinfo failed. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
2025-10-19 18:33:26,687 - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=kafka:9092 <connecting> [unspecified None]>: DNS lookup failed for kafka:9092 (0)
2025-10-19 18:33:26,687 - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=kafka:9092 <connecting> [unspecified None]>: Closing connection. KafkaConnectionError: DNS failure
2025-10-19 18:33:26,687 - Node 1 connection failed -- refreshing metadata
2025-10-19 18:33:29,425 - DNS lookup failed for kafka:9092, exception was [Errno 11001] getaddrinfo failed. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
2025-10-19 18:33:29,425 - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=kafka:9092 <connecting> [unspecified None]>: DNS lookup failed for kafka:9092 (0)
2025-10-19 18:33:29,425 - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=kafka:9092 <connecting> [unspecified None]>: Closing connection. KafkaConnectionError: DNS failure
2025-10-19 18:33:29,425 - Node 1 connection failed -- refreshing metadata
2025-10-19 18:33:32,180 - DNS lookup failed for kafka:9092, exception was [Errno 11001] getaddrinfo failed. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
2025-10-19 18:33:32,180 - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=kafka:9092 <connecting> [unspecified None]>: DNS lookup failed for kafka:9092 (0)
2025-10-19 18:33:32,180 - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=kafka:9092 <connecting> [unspecified None]>: Closing connection. KafkaConnectionError: DNS failure
2025-10-19 18:33:32,180 - Node 1 connection failed -- refreshing metadata
2025-10-19 18:33:39,086 - DNS lookup failed for kafka:9092, exception was [Errno 11001] getaddrinfo failed. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
2025-10-19 18:33:39,086 - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=kafka:9092 <connecting> [unspecified None]>: DNS lookup failed for kafka:9092 (0)
2025-10-19 18:33:39,086 - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=kafka:9092 <connecting> [unspecified None]>: Closing connection. KafkaConnectionError: DNS failure
2025-10-19 18:33:39,086 - Node 1 connection failed -- refreshing metadata
2025-10-19 18:33:41,834 - DNS lookup failed for kafka:9092, exception was [Errno 11001] getaddrinfo failed. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
2025-10-19 18:33:41,834 - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=kafka:9092 <connecting> [unspecified None]>: DNS lookup failed for kafka:9092 (0)
2025-10-19 18:33:41,834 - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=kafka:9092 <connecting> [unspecified None]>: Closing connection. KafkaConnectionError: DNS failure
2025-10-19 18:33:41,835 - Node 1 connection failed -- refreshing metadata
2025-10-19 18:33:49,412 - DNS lookup failed for kafka:9092, exception was [Errno 11001] getaddrinfo failed. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
2025-10-19 18:33:49,412 - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=kafka:9092 <connecting> [unspecified None]>: DNS lookup failed for kafka:9092 (0)
2025-10-19 18:33:49,412 - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=kafka:9092 <connecting> [unspecified None]>: Closing connection. KafkaConnectionError: DNS failure
2025-10-19 18:33:49,413 - Node 1 connection failed -- refreshing metadata
2025-10-19 18:34:06,468 - DNS lookup failed for kafka:9092, exception was [Errno 11001] getaddrinfo failed. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
2025-10-19 18:34:06,469 - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=kafka:9092 <connecting> [unspecified None]>: DNS lookup failed for kafka:9092 (0)
2025-10-19 18:34:06,469 - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=kafka:9092 <connecting> [unspecified None]>: Closing connection. KafkaConnectionError: DNS failure
2025-10-19 18:34:06,469 - Node 1 connection failed -- refreshing metadata
2025-10-19 18:34:11,207 - Error: KafkaTimeoutError: Failed to update metadata after 60.0 secs.
2025-10-19 18:34:33,273 - DNS lookup failed for kafka:9092, exception was [Errno 11001] getaddrinfo failed. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
2025-10-19 18:34:33,273 - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=kafka:9092 <connecting> [unspecified None]>: DNS lookup failed for kafka:9092 (0)
2025-10-19 18:34:33,273 - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=kafka:9092 <connecting> [unspecified None]>: Closing connection. KafkaConnectionError: DNS failure
2025-10-19 18:34:33,273 - Node 1 connection failed -- refreshing metadata
2025-10-19 18:35:05,449 - DNS lookup failed for kafka:9092, exception was [Errno 11001] getaddrinfo failed. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
2025-10-19 18:35:05,449 - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=kafka:9092 <connecting> [unspecified None]>: DNS lookup failed for kafka:9092 (0)
2025-10-19 18:35:05,449 - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=kafka:9092 <connecting> [unspecified None]>: Closing connection. KafkaConnectionError: DNS failure
2025-10-19 18:35:05,449 - Node 1 connection failed -- refreshing metadata
2025-10-19 18:35:16,837 - Error: KafkaTimeoutError: Failed to update metadata after 60.0 secs.
2025-10-19 18:39:55,380 - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: connecting to localhost:9092 [('::1', 9092, 0, 0) IPv6]
2025-10-19 18:40:44,056 - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: connecting to localhost:9092 [('::1', 9092, 0, 0) IPv6]
2025-10-19 18:40:44,067 - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=localhost:9092 <checking_api_versions_recv> [IPv6 ('::1', 9092, 0, 0)]>: Broker version identified as 2.6
2025-10-19 18:40:44,067 - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=localhost:9092 <connected> [IPv6 ('::1', 9092, 0, 0)]>: Connection complete.
2025-10-19 18:40:51,950 - DNS lookup failed for kafka:9092, exception was [Errno 11001] getaddrinfo failed. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
2025-10-19 18:40:51,951 - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=kafka:9092 <connecting> [unspecified None]>: DNS lookup failed for kafka:9092 (0)
2025-10-19 18:40:51,951 - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=kafka:9092 <connecting> [unspecified None]>: Closing connection. KafkaConnectionError: DNS failure
2025-10-19 18:40:51,951 - Node 1 connection failed -- refreshing metadata
2025-10-19 18:40:54,709 - DNS lookup failed for kafka:9092, exception was [Errno 11001] getaddrinfo failed. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
2025-10-19 18:40:54,709 - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=kafka:9092 <connecting> [unspecified None]>: DNS lookup failed for kafka:9092 (0)
2025-10-19 18:40:54,709 - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=kafka:9092 <connecting> [unspecified None]>: Closing connection. KafkaConnectionError: DNS failure
2025-10-19 18:40:54,709 - Node 1 connection failed -- refreshing metadata
2025-10-19 18:40:57,453 - DNS lookup failed for kafka:9092, exception was [Errno 11001] getaddrinfo failed. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
2025-10-19 18:40:57,454 - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=kafka:9092 <connecting> [unspecified None]>: DNS lookup failed for kafka:9092 (0)
2025-10-19 18:40:57,454 - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=kafka:9092 <connecting> [unspecified None]>: Closing connection. KafkaConnectionError: DNS failure
2025-10-19 18:40:57,454 - Node 1 connection failed -- refreshing metadata
2025-10-19 18:41:00,217 - DNS lookup failed for kafka:9092, exception was [Errno 11001] getaddrinfo failed. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
2025-10-19 18:41:00,217 - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=kafka:9092 <connecting> [unspecified None]>: DNS lookup failed for kafka:9092 (0)
2025-10-19 18:41:00,217 - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=kafka:9092 <connecting> [unspecified None]>: Closing connection. KafkaConnectionError: DNS failure
2025-10-19 18:41:00,217 - Node 1 connection failed -- refreshing metadata
2025-10-19 18:41:02,969 - DNS lookup failed for kafka:9092, exception was [Errno 11001] getaddrinfo failed. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
2025-10-19 18:41:02,969 - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=kafka:9092 <connecting> [unspecified None]>: DNS lookup failed for kafka:9092 (0)
2025-10-19 18:41:02,969 - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=kafka:9092 <connecting> [unspecified None]>: Closing connection. KafkaConnectionError: DNS failure
2025-10-19 18:41:02,969 - Node 1 connection failed -- refreshing metadata
2025-10-19 18:41:05,731 - DNS lookup failed for kafka:9092, exception was [Errno 11001] getaddrinfo failed. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
2025-10-19 18:41:05,731 - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=kafka:9092 <connecting> [unspecified None]>: DNS lookup failed for kafka:9092 (0)
2025-10-19 18:41:05,731 - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=kafka:9092 <connecting> [unspecified None]>: Closing connection. KafkaConnectionError: DNS failure
2025-10-19 18:41:05,732 - Node 1 connection failed -- refreshing metadata
2025-10-19 18:41:12,605 - DNS lookup failed for kafka:9092, exception was [Errno 11001] getaddrinfo failed. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
2025-10-19 18:41:12,605 - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=kafka:9092 <connecting> [unspecified None]>: DNS lookup failed for kafka:9092 (0)
2025-10-19 18:41:12,605 - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=kafka:9092 <connecting> [unspecified None]>: Closing connection. KafkaConnectionError: DNS failure
2025-10-19 18:41:12,605 - Node 1 connection failed -- refreshing metadata
2025-10-19 18:41:15,347 - DNS lookup failed for kafka:9092, exception was [Errno 11001] getaddrinfo failed. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
2025-10-19 18:41:15,347 - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=kafka:9092 <connecting> [unspecified None]>: DNS lookup failed for kafka:9092 (0)
2025-10-19 18:41:15,347 - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=kafka:9092 <connecting> [unspecified None]>: Closing connection. KafkaConnectionError: DNS failure
2025-10-19 18:41:15,347 - Node 1 connection failed -- refreshing metadata
2025-10-19 18:41:21,597 - DNS lookup failed for kafka:9092, exception was [Errno 11001] getaddrinfo failed. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
2025-10-19 18:41:21,597 - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=kafka:9092 <connecting> [unspecified None]>: DNS lookup failed for kafka:9092 (0)
2025-10-19 18:41:21,597 - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=kafka:9092 <connecting> [unspecified None]>: Closing connection. KafkaConnectionError: DNS failure
2025-10-19 18:41:21,597 - Node 1 connection failed -- refreshing metadata
2025-10-19 18:41:37,040 - DNS lookup failed for kafka:9092, exception was [Errno 11001] getaddrinfo failed. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
2025-10-19 18:41:37,040 - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=kafka:9092 <connecting> [unspecified None]>: DNS lookup failed for kafka:9092 (0)
2025-10-19 18:41:37,040 - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=kafka:9092 <connecting> [unspecified None]>: Closing connection. KafkaConnectionError: DNS failure
2025-10-19 18:41:37,040 - Node 1 connection failed -- refreshing metadata
2025-10-19 18:41:44,709 - Error: KafkaTimeoutError: Failed to update metadata after 60.0 secs.
2025-10-19 18:42:02,740 - DNS lookup failed for kafka:9092, exception was [Errno 11001] getaddrinfo failed. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
2025-10-19 18:42:02,740 - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=kafka:9092 <connecting> [unspecified None]>: DNS lookup failed for kafka:9092 (0)
2025-10-19 18:42:02,740 - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=kafka:9092 <connecting> [unspecified None]>: Closing connection. KafkaConnectionError: DNS failure
2025-10-19 18:42:02,740 - Node 1 connection failed -- refreshing metadata
2025-10-19 18:42:27,832 - DNS lookup failed for kafka:9092, exception was [Errno 11001] getaddrinfo failed. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
2025-10-19 18:42:27,832 - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=kafka:9092 <connecting> [unspecified None]>: DNS lookup failed for kafka:9092 (0)
2025-10-19 18:42:27,832 - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=kafka:9092 <connecting> [unspecified None]>: Closing connection. KafkaConnectionError: DNS failure
2025-10-19 18:42:27,833 - Node 1 connection failed -- refreshing metadata
2025-10-19 18:42:50,231 - Error: KafkaTimeoutError: Failed to update metadata after 60.0 secs.
2025-10-19 18:43:08,392 - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: connecting to localhost:9092 [('::1', 9092, 0, 0) IPv6]
2025-10-19 18:43:08,400 - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=localhost:9092 <checking_api_versions_recv> [IPv6 ('::1', 9092, 0, 0)]>: Broker version identified as 2.6
2025-10-19 18:43:08,401 - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=localhost:9092 <connected> [IPv6 ('::1', 9092, 0, 0)]>: Connection complete.
2025-10-19 18:43:11,751 - DNS lookup failed for kafka:9092, exception was [Errno 11001] getaddrinfo failed. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
2025-10-19 18:43:11,751 - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=kafka:9092 <connecting> [unspecified None]>: DNS lookup failed for kafka:9092 (0)
2025-10-19 18:43:11,751 - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=kafka:9092 <connecting> [unspecified None]>: Closing connection. KafkaConnectionError: DNS failure
2025-10-19 18:43:11,752 - Node 1 connection failed -- refreshing metadata
2025-10-19 18:43:14,534 - DNS lookup failed for kafka:9092, exception was [Errno 11001] getaddrinfo failed. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
2025-10-19 18:43:14,534 - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=kafka:9092 <connecting> [unspecified None]>: DNS lookup failed for kafka:9092 (0)
2025-10-19 18:43:14,534 - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=kafka:9092 <connecting> [unspecified None]>: Closing connection. KafkaConnectionError: DNS failure
2025-10-19 18:43:14,534 - Node 1 connection failed -- refreshing metadata
2025-10-19 18:43:21,414 - DNS lookup failed for kafka:9092, exception was [Errno 11001] getaddrinfo failed. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
2025-10-19 18:43:21,414 - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=kafka:9092 <connecting> [unspecified None]>: DNS lookup failed for kafka:9092 (0)
2025-10-19 18:43:21,414 - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=kafka:9092 <connecting> [unspecified None]>: Closing connection. KafkaConnectionError: DNS failure
2025-10-19 18:43:21,415 - Node 1 connection failed -- refreshing metadata
2025-10-19 18:43:24,158 - DNS lookup failed for kafka:9092, exception was [Errno 11001] getaddrinfo failed. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
2025-10-19 18:43:24,158 - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=kafka:9092 <connecting> [unspecified None]>: DNS lookup failed for kafka:9092 (0)
2025-10-19 18:43:24,158 - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=kafka:9092 <connecting> [unspecified None]>: Closing connection. KafkaConnectionError: DNS failure
2025-10-19 18:43:24,158 - Node 1 connection failed -- refreshing metadata
2025-10-19 18:43:26,902 - DNS lookup failed for kafka:9092, exception was [Errno 11001] getaddrinfo failed. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
2025-10-19 18:43:26,902 - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=kafka:9092 <connecting> [unspecified None]>: DNS lookup failed for kafka:9092 (0)
2025-10-19 18:43:26,902 - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=kafka:9092 <connecting> [unspecified None]>: Closing connection. KafkaConnectionError: DNS failure
2025-10-19 18:43:26,902 - Node 1 connection failed -- refreshing metadata
2025-10-19 18:43:29,628 - DNS lookup failed for kafka:9092, exception was [Errno 11001] getaddrinfo failed. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
2025-10-19 18:43:29,628 - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=kafka:9092 <connecting> [unspecified None]>: DNS lookup failed for kafka:9092 (0)
2025-10-19 18:43:29,628 - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=kafka:9092 <connecting> [unspecified None]>: Closing connection. KafkaConnectionError: DNS failure
2025-10-19 18:43:29,629 - Node 1 connection failed -- refreshing metadata
2025-10-19 18:43:32,382 - DNS lookup failed for kafka:9092, exception was [Errno 11001] getaddrinfo failed. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
2025-10-19 18:43:32,383 - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=kafka:9092 <connecting> [unspecified None]>: DNS lookup failed for kafka:9092 (0)
2025-10-19 18:43:32,383 - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=kafka:9092 <connecting> [unspecified None]>: Closing connection. KafkaConnectionError: DNS failure
2025-10-19 18:43:32,383 - Node 1 connection failed -- refreshing metadata
2025-10-19 18:43:36,119 - DNS lookup failed for kafka:9092, exception was [Errno 11001] getaddrinfo failed. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
2025-10-19 18:43:36,120 - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=kafka:9092 <connecting> [unspecified None]>: DNS lookup failed for kafka:9092 (0)
2025-10-19 18:43:36,120 - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=kafka:9092 <connecting> [unspecified None]>: Closing connection. KafkaConnectionError: DNS failure
2025-10-19 18:43:36,120 - Node 1 connection failed -- refreshing metadata
2025-10-19 18:43:47,486 - DNS lookup failed for kafka:9092, exception was [Errno 11001] getaddrinfo failed. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
2025-10-19 18:43:47,486 - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=kafka:9092 <connecting> [unspecified None]>: DNS lookup failed for kafka:9092 (0)
2025-10-19 18:43:47,486 - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=kafka:9092 <connecting> [unspecified None]>: Closing connection. KafkaConnectionError: DNS failure
2025-10-19 18:43:47,486 - Node 1 connection failed -- refreshing metadata
2025-10-19 18:43:57,225 - DNS lookup failed for kafka:9092, exception was [Errno 11001] getaddrinfo failed. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
2025-10-19 18:43:57,225 - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=kafka:9092 <connecting> [unspecified None]>: DNS lookup failed for kafka:9092 (0)
2025-10-19 18:43:57,225 - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=kafka:9092 <connecting> [unspecified None]>: Closing connection. KafkaConnectionError: DNS failure
2025-10-19 18:43:57,225 - Node 1 connection failed -- refreshing metadata
2025-10-19 18:44:09,053 - Error: KafkaTimeoutError: Failed to update metadata after 60.0 secs.
2025-10-19 18:44:29,023 - DNS lookup failed for kafka:9092, exception was [Errno 11001] getaddrinfo failed. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
2025-10-19 18:44:29,023 - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=kafka:9092 <connecting> [unspecified None]>: DNS lookup failed for kafka:9092 (0)
2025-10-19 18:44:29,023 - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=kafka:9092 <connecting> [unspecified None]>: Closing connection. KafkaConnectionError: DNS failure
2025-10-19 18:44:29,024 - Node 1 connection failed -- refreshing metadata
2025-10-19 18:46:55,439 - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: connecting to localhost:9092 [('::1', 9092, 0, 0) IPv6]
2025-10-19 18:46:55,453 - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=localhost:9092 <checking_api_versions_recv> [IPv6 ('::1', 9092, 0, 0)]>: Broker version identified as 2.6
2025-10-19 18:46:55,453 - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=localhost:9092 <connected> [IPv6 ('::1', 9092, 0, 0)]>: Connection complete.
2025-10-19 18:47:03,584 - DNS lookup failed for kafka:9092, exception was [Errno 11001] getaddrinfo failed. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
2025-10-19 18:47:03,584 - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=kafka:9092 <connecting> [unspecified None]>: DNS lookup failed for kafka:9092 (0)
2025-10-19 18:47:03,584 - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=kafka:9092 <connecting> [unspecified None]>: Closing connection. KafkaConnectionError: DNS failure
2025-10-19 18:47:03,584 - Node 1 connection failed -- refreshing metadata
2025-10-19 18:47:06,349 - DNS lookup failed for kafka:9092, exception was [Errno 11001] getaddrinfo failed. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
2025-10-19 18:47:06,349 - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=kafka:9092 <connecting> [unspecified None]>: DNS lookup failed for kafka:9092 (0)
2025-10-19 18:47:06,349 - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=kafka:9092 <connecting> [unspecified None]>: Closing connection. KafkaConnectionError: DNS failure
2025-10-19 18:47:06,350 - Node 1 connection failed -- refreshing metadata
2025-10-19 18:47:09,091 - DNS lookup failed for kafka:9092, exception was [Errno 11001] getaddrinfo failed. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
2025-10-19 18:47:09,091 - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=kafka:9092 <connecting> [unspecified None]>: DNS lookup failed for kafka:9092 (0)
2025-10-19 18:47:09,091 - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=kafka:9092 <connecting> [unspecified None]>: Closing connection. KafkaConnectionError: DNS failure
2025-10-19 18:47:09,092 - Node 1 connection failed -- refreshing metadata
2025-10-19 18:47:11,850 - DNS lookup failed for kafka:9092, exception was [Errno 11001] getaddrinfo failed. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
2025-10-19 18:47:11,850 - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=kafka:9092 <connecting> [unspecified None]>: DNS lookup failed for kafka:9092 (0)
2025-10-19 18:47:11,850 - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=kafka:9092 <connecting> [unspecified None]>: Closing connection. KafkaConnectionError: DNS failure
2025-10-19 18:47:11,850 - Node 1 connection failed -- refreshing metadata
2025-10-19 18:47:14,590 - DNS lookup failed for kafka:9092, exception was [Errno 11001] getaddrinfo failed. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
2025-10-19 18:47:14,590 - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=kafka:9092 <connecting> [unspecified None]>: DNS lookup failed for kafka:9092 (0)
2025-10-19 18:47:14,590 - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=kafka:9092 <connecting> [unspecified None]>: Closing connection. KafkaConnectionError: DNS failure
2025-10-19 18:47:14,590 - Node 1 connection failed -- refreshing metadata
2025-10-19 18:47:17,340 - DNS lookup failed for kafka:9092, exception was [Errno 11001] getaddrinfo failed. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
2025-10-19 18:47:17,340 - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=kafka:9092 <connecting> [unspecified None]>: DNS lookup failed for kafka:9092 (0)
2025-10-19 18:47:17,340 - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=kafka:9092 <connecting> [unspecified None]>: Closing connection. KafkaConnectionError: DNS failure
2025-10-19 18:47:17,340 - Node 1 connection failed -- refreshing metadata
2025-10-19 18:47:24,200 - DNS lookup failed for kafka:9092, exception was [Errno 11001] getaddrinfo failed. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
2025-10-19 18:47:24,200 - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=kafka:9092 <connecting> [unspecified None]>: DNS lookup failed for kafka:9092 (0)
2025-10-19 18:47:24,200 - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=kafka:9092 <connecting> [unspecified None]>: Closing connection. KafkaConnectionError: DNS failure
2025-10-19 18:47:24,200 - Node 1 connection failed -- refreshing metadata
2025-10-19 18:47:26,939 - DNS lookup failed for kafka:9092, exception was [Errno 11001] getaddrinfo failed. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
2025-10-19 18:47:26,939 - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=kafka:9092 <connecting> [unspecified None]>: DNS lookup failed for kafka:9092 (0)
2025-10-19 18:47:26,939 - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=kafka:9092 <connecting> [unspecified None]>: Closing connection. KafkaConnectionError: DNS failure
2025-10-19 18:47:26,939 - Node 1 connection failed -- refreshing metadata
2025-10-19 18:47:34,600 - DNS lookup failed for kafka:9092, exception was [Errno 11001] getaddrinfo failed. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
2025-10-19 18:47:34,601 - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=kafka:9092 <connecting> [unspecified None]>: DNS lookup failed for kafka:9092 (0)
2025-10-19 18:47:34,601 - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=kafka:9092 <connecting> [unspecified None]>: Closing connection. KafkaConnectionError: DNS failure
2025-10-19 18:47:34,601 - Node 1 connection failed -- refreshing metadata
2025-10-19 18:50:26,130 - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: connecting to localhost:9092 [('::1', 9092, 0, 0) IPv6]
2025-10-19 18:50:26,138 - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=localhost:9092 <checking_api_versions_recv> [IPv6 ('::1', 9092, 0, 0)]>: Broker version identified as 2.6
2025-10-19 18:50:26,138 - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=localhost:9092 <connected> [IPv6 ('::1', 9092, 0, 0)]>: Connection complete.
2025-10-19 18:50:33,972 - DNS lookup failed for kafka:9092, exception was [Errno 11001] getaddrinfo failed. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
2025-10-19 18:50:33,972 - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=kafka:9092 <connecting> [unspecified None]>: DNS lookup failed for kafka:9092 (0)
2025-10-19 18:50:33,972 - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=kafka:9092 <connecting> [unspecified None]>: Closing connection. KafkaConnectionError: DNS failure
2025-10-19 18:50:33,973 - Node 1 connection failed -- refreshing metadata
2025-10-19 18:50:36,719 - DNS lookup failed for kafka:9092, exception was [Errno 11001] getaddrinfo failed. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
2025-10-19 18:50:36,719 - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=kafka:9092 <connecting> [unspecified None]>: DNS lookup failed for kafka:9092 (0)
2025-10-19 18:50:36,719 - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=kafka:9092 <connecting> [unspecified None]>: Closing connection. KafkaConnectionError: DNS failure
2025-10-19 18:50:36,720 - Node 1 connection failed -- refreshing metadata
2025-10-19 18:50:39,462 - DNS lookup failed for kafka:9092, exception was [Errno 11001] getaddrinfo failed. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
2025-10-19 18:50:39,462 - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=kafka:9092 <connecting> [unspecified None]>: DNS lookup failed for kafka:9092 (0)
2025-10-19 18:50:39,462 - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=kafka:9092 <connecting> [unspecified None]>: Closing connection. KafkaConnectionError: DNS failure
2025-10-19 18:50:39,462 - Node 1 connection failed -- refreshing metadata
2025-10-19 18:50:42,234 - DNS lookup failed for kafka:9092, exception was [Errno 11001] getaddrinfo failed. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
2025-10-19 18:50:42,234 - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=kafka:9092 <connecting> [unspecified None]>: DNS lookup failed for kafka:9092 (0)
2025-10-19 18:50:42,234 - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=kafka:9092 <connecting> [unspecified None]>: Closing connection. KafkaConnectionError: DNS failure
2025-10-19 18:50:42,234 - Node 1 connection failed -- refreshing metadata
2025-10-19 18:50:44,985 - DNS lookup failed for kafka:9092, exception was [Errno 11001] getaddrinfo failed. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
2025-10-19 18:50:44,986 - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=kafka:9092 <connecting> [unspecified None]>: DNS lookup failed for kafka:9092 (0)
2025-10-19 18:50:44,986 - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=kafka:9092 <connecting> [unspecified None]>: Closing connection. KafkaConnectionError: DNS failure
2025-10-19 18:50:44,986 - Node 1 connection failed -- refreshing metadata
2025-10-19 18:50:47,734 - DNS lookup failed for kafka:9092, exception was [Errno 11001] getaddrinfo failed. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
2025-10-19 18:50:47,734 - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=kafka:9092 <connecting> [unspecified None]>: DNS lookup failed for kafka:9092 (0)
2025-10-19 18:50:47,734 - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=kafka:9092 <connecting> [unspecified None]>: Closing connection. KafkaConnectionError: DNS failure
2025-10-19 18:50:47,734 - Node 1 connection failed -- refreshing metadata
2025-10-19 18:50:54,648 - DNS lookup failed for kafka:9092, exception was [Errno 11001] getaddrinfo failed. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
2025-10-19 18:50:54,648 - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=kafka:9092 <connecting> [unspecified None]>: DNS lookup failed for kafka:9092 (0)
2025-10-19 18:50:54,648 - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=kafka:9092 <connecting> [unspecified None]>: Closing connection. KafkaConnectionError: DNS failure
2025-10-19 18:50:54,648 - Node 1 connection failed -- refreshing metadata
2025-10-19 18:50:57,407 - DNS lookup failed for kafka:9092, exception was [Errno 11001] getaddrinfo failed. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
2025-10-19 18:50:57,407 - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=kafka:9092 <connecting> [unspecified None]>: DNS lookup failed for kafka:9092 (0)
2025-10-19 18:50:57,408 - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=kafka:9092 <connecting> [unspecified None]>: Closing connection. KafkaConnectionError: DNS failure
2025-10-19 18:50:57,408 - Node 1 connection failed -- refreshing metadata
2025-10-19 18:51:04,861 - DNS lookup failed for kafka:9092, exception was [Errno 11001] getaddrinfo failed. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
2025-10-19 18:51:04,861 - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=kafka:9092 <connecting> [unspecified None]>: DNS lookup failed for kafka:9092 (0)
2025-10-19 18:51:04,861 - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=kafka:9092 <connecting> [unspecified None]>: Closing connection. KafkaConnectionError: DNS failure
2025-10-19 18:51:04,861 - Node 1 connection failed -- refreshing metadata
2025-10-19 18:51:22,077 - DNS lookup failed for kafka:9092, exception was [Errno 11001] getaddrinfo failed. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
2025-10-19 18:51:22,077 - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=kafka:9092 <connecting> [unspecified None]>: DNS lookup failed for kafka:9092 (0)
2025-10-19 18:51:22,077 - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=kafka:9092 <connecting> [unspecified None]>: Closing connection. KafkaConnectionError: DNS failure
2025-10-19 18:51:22,077 - Node 1 connection failed -- refreshing metadata
2025-10-19 18:51:26,737 - Error: KafkaTimeoutError: Failed to update metadata after 60.0 secs.
2025-10-19 18:51:43,963 - DNS lookup failed for kafka:9092, exception was [Errno 11001] getaddrinfo failed. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
2025-10-19 18:51:43,963 - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=kafka:9092 <connecting> [unspecified None]>: DNS lookup failed for kafka:9092 (0)
2025-10-19 18:51:43,963 - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=kafka:9092 <connecting> [unspecified None]>: Closing connection. KafkaConnectionError: DNS failure
2025-10-19 18:51:43,963 - Node 1 connection failed -- refreshing metadata
2025-10-19 18:58:20,258 - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: connecting to localhost:9092 [('::1', 9092, 0, 0) IPv6]
2025-10-19 18:58:20,266 - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=localhost:9092 <checking_api_versions_recv> [IPv6 ('::1', 9092, 0, 0)]>: Broker version identified as 2.6
2025-10-19 18:58:20,266 - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=localhost:9092 <connected> [IPv6 ('::1', 9092, 0, 0)]>: Connection complete.
2025-10-19 18:58:20,890 - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: connecting to localhost:9092 [('::1', 9092, 0, 0) IPv6]
2025-10-19 18:58:20,890 - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:9092 <connected> [IPv6 ('::1', 9092, 0, 0)]>: Connection complete.
2025-10-19 18:58:20,890 - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=localhost:9092 <connected> [IPv6 ('::1', 9092, 0, 0)]>: Closing connection. 
2025-10-19 18:58:20,912 - {'camera': 'HCMC_5deb576d1dc17d7c5515acfa', 'timestamp': '2025-10-19T11:58:20.888869', 'counts': {'car': 20, 'motorcycle': 6, 'truck': 1}}
2025-10-19 18:58:26,445 - {'camera': 'HCMC_5deb576d1dc17d7c5515acfa', 'timestamp': '2025-10-19T11:58:26.441892', 'counts': {'car': 19, 'bus': 1, 'motorcycle': 20}}
2025-10-19 18:58:31,954 - {'camera': 'HCMC_5deb576d1dc17d7c5515acfa', 'timestamp': '2025-10-19T11:58:31.950683', 'counts': {'car': 19, 'bus': 1, 'motorcycle': 20}}
2025-10-19 18:58:37,470 - {'camera': 'HCMC_5deb576d1dc17d7c5515acfa', 'timestamp': '2025-10-19T11:58:37.466296', 'counts': {'car': 19, 'bus': 1, 'motorcycle': 20}}
2025-10-19 18:58:43,008 - {'camera': 'HCMC_5deb576d1dc17d7c5515acfa', 'timestamp': '2025-10-19T11:58:43.004745', 'counts': {'car': 25, 'motorcycle': 13}}
2025-10-19 18:58:48,516 - {'camera': 'HCMC_5deb576d1dc17d7c5515acfa', 'timestamp': '2025-10-19T11:58:48.512929', 'counts': {'car': 25, 'motorcycle': 13}}
2025-10-19 18:58:54,079 - {'camera': 'HCMC_5deb576d1dc17d7c5515acfa', 'timestamp': '2025-10-19T11:58:54.075471', 'counts': {'motorcycle': 11, 'car': 9}}
2025-10-19 18:58:59,600 - {'camera': 'HCMC_5deb576d1dc17d7c5515acfa', 'timestamp': '2025-10-19T11:58:59.597033', 'counts': {'motorcycle': 11, 'car': 9}}
2025-10-19 18:59:05,140 - {'camera': 'HCMC_5deb576d1dc17d7c5515acfa', 'timestamp': '2025-10-19T11:59:05.136552', 'counts': {'car': 26, 'motorcycle': 4}}
2025-10-19 18:59:10,661 - {'camera': 'HCMC_5deb576d1dc17d7c5515acfa', 'timestamp': '2025-10-19T11:59:10.658048', 'counts': {'car': 26, 'motorcycle': 4}}
2025-10-19 18:59:16,256 - {'camera': 'HCMC_5deb576d1dc17d7c5515acfa', 'timestamp': '2025-10-19T11:59:16.252031', 'counts': {'car': 21}}
2025-10-19 18:59:21,845 - {'camera': 'HCMC_5deb576d1dc17d7c5515acfa', 'timestamp': '2025-10-19T11:59:21.840782', 'counts': {'car': 21}}
2025-10-19 18:59:27,422 - {'camera': 'HCMC_5deb576d1dc17d7c5515acfa', 'timestamp': '2025-10-19T11:59:27.418547', 'counts': {'car': 21}}
2025-10-19 18:59:32,997 - {'camera': 'HCMC_5deb576d1dc17d7c5515acfa', 'timestamp': '2025-10-19T11:59:32.993997', 'counts': {'car': 8, 'bus': 1, 'truck': 1, 'motorcycle': 2}}
2025-10-19 18:59:38,620 - {'camera': 'HCMC_5deb576d1dc17d7c5515acfa', 'timestamp': '2025-10-19T11:59:38.616656', 'counts': {'car': 8, 'bus': 1, 'truck': 1, 'motorcycle': 2}}
2025-10-19 18:59:44,148 - {'camera': 'HCMC_5deb576d1dc17d7c5515acfa', 'timestamp': '2025-10-19T11:59:44.144617', 'counts': {'car': 25, 'motorcycle': 12}}
2025-10-19 18:59:49,689 - {'camera': 'HCMC_5deb576d1dc17d7c5515acfa', 'timestamp': '2025-10-19T11:59:49.685646', 'counts': {'car': 25, 'motorcycle': 12}}
2025-10-19 18:59:55,294 - {'camera': 'HCMC_5deb576d1dc17d7c5515acfa', 'timestamp': '2025-10-19T11:59:55.291034', 'counts': {'car': 44, 'motorcycle': 41}}
2025-10-19 18:59:55,410 - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:9092 <connected> [IPv6 ('::1', 9092, 0, 0)]>: Closing connection. 
